### PR TITLE
massive update, almost from scratch

### PR DESCRIPTION
**Pull request by AkihiroSuda**
The new web site aims at putting the focus on end-users rather than on research engineers.
    
Notably, the new site contains the tutorials for several container implementations, and the glossary to explain the notoriously confusing jargons such as "slirp".
    
The tutorials slightly overlap with the existing documentation in the upstream projects, but the tutorials in this repo are (attempted to be) written in the same form across several container implementations, for ease of comparison.

## Theme
The hugo theme is changed to [Geekdocs](https://geekdocs.de/usage/getting-started/), because the previous theme doesn't seem to support TOC tree.

`./site/themes/hugo-geekdoc` contains the precompiled version of Geekdocs v0.4.0 without any modification.

## Preview
Run `make serve` to serve preview pages on http://localhost:1313 .

image

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@cyphar @giuseppe PTAL

**Comment by cyphar** [comment]
Looks pretty neat (though it wouldn't hurt to through and clean up some of the new text's grammar). We can also switch to using Netify for hosting rather than the current manual `gh-pages` setup.

**Comment by AkihiroSuda** [comment]
Needs help :)

**Comment by AkihiroSuda** [comment]
@cyphar @giuseppe PTAL (sorry this is huge)

**Comment by AkihiroSuda** [comment]
Updated to mention Docker v20.10 and https://github.com/rootless-containers/bypass4netns

**Review by cyphar — APPROVED** [review]
My general comment is that I think it could be reorganised and polished quite a bit, but in terms of accuracy and usefulness this is a massive improvement over the current website so I'm going to merge this even though I think it could be reworked quite a bit further (there are some minor grammatical mistakes as well -- but we can also clean those up separately).

Thanks @AkihiroSuda and sorry for sitting on this for a while -- I was trying to decide whether it'd be more helpful to send a massive diff for you to apply or whether it'd be simpler to just merge this and move on from there.

**Comment by cyphar** [comment]
I also think that you should've used submodules for GeekDocs (since it means we don't vendor other people's code) but as I said above we can fix this in a separate PR.

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by cyphar** [comment]
Ah we can't trivially use submodules because GeekDocs requires you to do some build steps with `gulp` (Node.js). I'll just leave it as-is for now.

**Pull request merged**
